name: hydrated_notifier
description: An extension to the state_notifier library which automatically persists and restores states.
version: 1.0.1
repository: https://github.com/herveGuigoz/hydrated_notifier

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.1.0
  state_notifier: ^0.7.0
  synchronized: ^3.0.0

dev_dependencies:
  meta: ^1.7.0
  mocktail: ^0.2.0
  path: ^1.8.0
  test: ^1.21.1
  uuid: ^3.0.5